In [1]:
import torch

In [2]:
X = torch.tensor([[[1, 2, 3], [4, 5, 6]]])
#.shape tells you how many elements there are along each dimension (axis) of a tensor
X.ndim, X.shape

(3, torch.Size([1, 2, 3]))

In [3]:
X = torch.tensor([[[1, 2, 3], [4, 5, 6], [1, 1, 1]]])
X.ndim, X.shape

(3, torch.Size([1, 3, 3]))

In [4]:
X[0], X[0, 0], X[0, 0, 2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [1, 1, 1]]),
 tensor([1, 2, 3]),
 tensor(3))

In [5]:
rand_X = torch.rand(3, 4)
rand_X

tensor([[0.1926, 0.5595, 0.3523, 0.4586],
        [0.3616, 0.1859, 0.9321, 0.6322],
        [0.5837, 0.9596, 0.2566, 0.3063]])

In [6]:
rand_X = torch.rand(size = (3, 4), generator= None)
rand_X

tensor([[0.6267, 0.1409, 0.4298, 0.8864],
        [0.5735, 0.2192, 0.4548, 0.0655],
        [0.6832, 0.9734, 0.7655, 0.0620]])

In [7]:
rand_X = torch.rand(size = (3, 4), generator = torch.Generator().manual_seed(42))
rand_X

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [8]:
# tensor of a certain type with the same shape as another tensor

zeros = torch.zeros_like(input=rand_X)
zeros 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])

torch.matmul(a, b)

tensor(14)

In [10]:
X = torch.arange(1, 11)
X_reshaped = X.reshape(2, 5)
X_reshaped

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [11]:
# reshape and view works same. Only diff is view of a tensor shares the same memory as the original input
Z = X.view(2, 5)
Z[0][0] = 100
Z, X

(tensor([[100,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10]]),
 tensor([100,   2,   3,   4,   5,   6,   7,   8,   9,  10]))

In [12]:
# setup device agonostics code (good practice)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [13]:
tensor_cpu = torch.tensor([1, 2, 3])
tensor_cpu, tensor_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [14]:
tensor_gpu = tensor_cpu.to(device)
tensor_gpu, tensor_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [15]:
!nvidia-smi

Wed Jul 29 06:22:46 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.159.04             Driver Version: 580.159.04     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P0             25W /   70W |     107MiB /  15360MiB |      3%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----